name: 'Check HTML Links action'
description: 'A simple way to check for dead links in the documentation of your repository'
inputs:
  doc-folder:
    description: 'location of the documentation folder'
    required: false
    default: 'dist'
# outputs:
  # result:
    # description: 'complete console output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.doc-folder }}