name: 'Check HTML Links action'
description: 'A simple way to check for dead links in the documentation of your repository'
author: 'Modern Web (https://modern-web.dev)'
branding:
  icon: 'bookmark'  
  color: 'blue' 
inputs:
  doc-folder:
    description: 'location of the documentation folder'
    required: false
    default: 'dist'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.doc-folder }}